### ISSUE TITLE
Standalone largetype utility?

### ISSUE THREAD

**Issue by twilsonco** [dbader/large-type.com#12]
This isn't really a request; more of a question. Would it be a lot of work to turn this into a standalone CLI utility? One that overlays the provided text as large type on screen, then dismissing when the user clicks somewhere outside the resulting large type window.

**Comment by BradKML** [comment]
Considering that https://www.101soundboards.com/ and others have an install function, why not?

**Comment by dbader** [comment]
If you're on macOS, check out https://www.alfredapp.com/help/features/large-type/

**Comment by twilsonco** [comment]
> If you're on macOS, check out https://www.alfredapp.com/help/features/large-type/

Oh that's nice. Didn't realize that was in there; been an Alfred user for years!
