### ISSUE TITLE
emojis are not working, while os and browser supports it

### ISSUE THREAD

**Issue by iamstarkov** [dbader/large-type.com#5]
http://large-type.com/#meow%20%F0%9F%90%B1
![screen shot 2016-03-18 at 13 01 54](https://cloud.githubusercontent.com/assets/559321/13877194/9d13bbf6-ed09-11e5-81f6-885594e857d0.png)

**Comment by dbader** [comment]
Thanks for reporting this @iamstarkov! It would be great to get emojis to work. So much more fun :smiley: 

I think this has to do with `split()` acting weird with strings containing emojii:

``` js
'😃'.split('')
["�", "�"]
```

**Comment by dbader** [comment]
Some more insight into this: https://stackoverflow.com/questions/34421887/splitting-emoji-safely

**Comment by dbader** [comment]
In ES6 we could use a `for ... of` loop to iterate over symbols:

``` js
var arr = []; for (let chr of "😃😃😃😃") arr.push(chr); arr
["😃", "😃", "😃", "😃"]
```

If we want to retain ES5 support, [spliddit](https://github.com/essdot/spliddit) seems like a good option.

**Comment by dbader** [comment]
Another fun issue is that Chrome (and probably other browsers too) have a font size limit above which they won't render emoji characters: https://twitter.com/wesbos/status/562660415813865472. I actually ran into this when testing because trying to render a single emoji character usually puts it above the size limit and it'll just display as a blank string.

**Comment by dbader** [comment]
Given the restrictions with native emoji rendering and also some cross-platform issues have come up it might make sense to start using something like Twitter's `twemoji`: https://github.com/twitter/twemoji

**Comment by nanoproductengineering** [comment]
I can confirm this issue on Firefox 52.01 on Ubuntu 16.10. http://large-type.com/#%F0%9F%98%80

**Comment by nekromoff** [comment]
This should help: https://github.com/orling/grapheme-splitter

**Comment by dbader** [comment]
We've got slightly better emoji support now:

https://large-type.com/#🌷🎁💩😜👍

But there are still problems with compound emoji. Ultimately we'll probably have to bring in something like grapheme-splitter, I think that's the way to go.

**Comment by iamstarkov** [comment]
hurray, thank you
