### ISSUE TITLE
Enable HTTPS

### ISSUE THREAD

**Issue by ondrejsika** [dbader/large-type.com#9]
Hi @dbader, this app is perfect. Could you enable HTTPS in Github Pages settings, please? Thanks, O.

**Comment by dbader** [comment]
Thanks for the heads up, currently waiting for GitHub to generate the cert :)

**Comment by dbader** [comment]
https://large-type.com should work now, will switch on http → https redirect soon

**Comment by ondrejsika** [comment]
Super! Thanks!
